server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514 # Listen on the exposed port
      listen_protocol: "udp"
      labels:
        job: systemd-journal # Apply a consistent label
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
      - source_labels: ['__syslog_message_facility']
        target_label: 'facility'

  - job_name: traefik
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik-access # identifies the log stream in Loki
          __path__: /var/log/traefik/access.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            request: request
            client_host: ClientHost
            router_name: RouterName
            service_name: ServiceName
      - labels:
          level:
          router_name:
          service_name: