server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

  - job_name: traefik
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik-access
          __path__: /var/log/traefik/access.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            request: request
            client_host: ClientHost
            router_name: RouterName
            service_name: ServiceName
      - labels:
          level:
          router_name:
          service_name: