global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mailmon'
    # The metrics endpoint is not at the root, so specify the path
    metrics_path: /metrics/
    static_configs:
      # Use the docker service name and internal port
      - targets: ['mailmon_mailmon:8000']